/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdv;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class JanelaVendas extends javax.swing.JFrame {
    
    public JanelaVendas() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        in_codigo_do_produto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vendas = new javax.swing.JTable();
        buinserir = new javax.swing.JButton();
        buexcluir = new javax.swing.JButton();
        bufinalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labtotal = new javax.swing.JLabel();
        bunova_venda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Codigo do Produto: ");

        in_codigo_do_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_codigo_do_produtoActionPerformed(evt);
            }
        });

        tabela_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_vendas);

        buinserir.setText("Inserir");
        buinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buinserirActionPerformed(evt);
            }
        });

        buexcluir.setText("Excluir");
        buexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buexcluirActionPerformed(evt);
            }
        });

        bufinalizar.setText("Finalizar venda");
        bufinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bufinalizarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Total da compra:");

        labtotal.setBackground(new java.awt.Color(255, 255, 255));
        labtotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labtotal.setForeground(new java.awt.Color(0, 0, 0));

        bunova_venda.setText("Nova venda");
        bunova_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunova_vendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(in_codigo_do_produto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buinserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bunova_venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bufinalizar)
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buinserir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(in_codigo_do_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bunova_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bufinalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buinserirActionPerformed
        String nome_produto = in_codigo_do_produto.getText();
        Produto produto = CadastroProduto.consulta(nome_produto);//retorna um objeto
        if (produto == null) {
            JOptionPane.showMessageDialog(null, "Não encontrado ", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel tb_vendas = (DefaultTableModel) tabela_vendas.getModel();
            Object[] dado = {produto.obterCodigo(), "1", produto.obterNome(), produto.obterPreco()};
            tb_vendas.addRow(dado);
            Double valor = Double.valueOf(produto.obterPreco());//valor do produto
            Vendas.somador(valor);//somador
            labtotal.setText(String.valueOf(Vendas.valorAtual()));//mostra o valor na tela
            
            Vendas.adicionarProduto_lista(produto);

        }
    }//GEN-LAST:event_buinserirActionPerformed

    private void buexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buexcluirActionPerformed
        if (tabela_vendas.getSelectedRow() != 1) {
            DefaultTableModel tb_vendas = (DefaultTableModel) tabela_vendas.getModel();
            int posicao = tabela_vendas.getSelectedRow();
            Produto produto_temp = Vendas.lista_vendas.get(posicao);//obter o objeto na lista
            
            tb_vendas.removeRow(posicao);//remove a linha da tabela 
            Vendas.removerProduto_lista(produto_temp);//remove o produto da lista
            
            Double valor = Double.parseDouble(produto_temp.obterPreco());//converte para decimal
            Vendas.subtrair(valor);//subtrai o valor total 
            labtotal.setText(String.valueOf(Vendas.valorAtual()));//mostra o valor na tela
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item ", "Aviso", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_buexcluirActionPerformed

    private void in_codigo_do_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_codigo_do_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_codigo_do_produtoActionPerformed

    private void bufinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bufinalizarActionPerformed
        FormaDePagamento pagamento = new FormaDePagamento();
        pagamento.setVisible(true);
        
    }//GEN-LAST:event_bufinalizarActionPerformed

    private void bunova_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunova_vendaActionPerformed
        DefaultTableModel tbprodutos = (DefaultTableModel) tabela_vendas.getModel();
        tbprodutos.setRowCount(0);
        Vendas.lista_vendas.clear();
        Vendas.valor_total = 0;
        labtotal.setText("");
    }//GEN-LAST:event_bunova_vendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buexcluir;
    private javax.swing.JButton bufinalizar;
    private javax.swing.JButton buinserir;
    private javax.swing.JButton bunova_venda;
    private javax.swing.JTextField in_codigo_do_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labtotal;
    private javax.swing.JTable tabela_vendas;
    // End of variables declaration//GEN-END:variables
}
